### ISSUE TITLE
Port to dotnet

### ISSUE THREAD

**Issue by abulhol** [codemerx/CodemerxDecompile#86]
The current version only builds for .NET Framework. 

This means on non-Windows systems, it can only be run using Mono. But Mono is slowly dying since the advent of `dotnet`.

I have tried myself to upgrade the solution to dotnet, but got stuck. Probably the solution uses Windows-specific dependencies (like Winforms) which have to be replaced or removed. 
It would be great if somebody familiar with the project could port it to `dotnet`.

**Comment by atdimitrov** [comment]
Hello. Which solution are you referring to? The main solution is `CodemerxDecompileEngine.sln` and it contains projects for both .NET Framework and .NET Core 3.1. So the solution is already ported to .NET Core. You may need to unload the .NET Framework projects in order to build without .NET Framework installed.

**Comment by abulhol** [comment]
@atdimitrov Nice! I hadn't noticed that support for .NET Core had been added in CodemerxDecompile. I had only tried worked with the old JustDecompileEngine solution. 
I will give this a try and see if it runs on Linux with .NET 6.0.
